### ISSUE TITLE
composer install not full

### ISSUE THREAD

**Issue by seyfcom** [genkgo/camt#119]
hi!
maybe a strange question for you

Why when I do a normal composer req ... I don't get the full code that is in the rep github?
I don't get the test folder for example.

PHP 7.4.26 (cli) (built: Nov 16 2021 18:15:31) ( ZTS Visual C++ 2017 x64 )
Laragon install.

**Comment by PowerKiKi** [comment]
This is on purpose, and is defined in https://github.com/genkgo/camt/blob/master/.gitattributes. Test file should be part of production install, because they might or might not be insecure. And most importantly they are not part of the public API, you should not use them yourself.

However if you want to use them to as a form of documentation, only for development purpose, you can do the following:

```sh
composer require --prefer-source genkgo/camt
[...]

ls -l vendor/genkgo/camt/test/

total 12
-rw-rw-r-- 1 kiki kiki  147 Apr 29 09:01 AbstractTestCase.php
drwxrwxr-x 6 kiki kiki 4096 Apr 29 09:01 Unit
drwxrwxr-x 2 kiki kiki 4096 Apr 29 09:01 Util
```

But don't keep the source version in your production builds.

**Comment by seyfcom** [comment]
Oh yes! thanks.. It is exactly on documentation purpose !
It all works, great! thank a lot
