### ISSUE TITLE
Remove scrunitzr

### ISSUE THREAD

**Issue by frederikbosch** [genkgo/camt#139]
Shall we remove it? I see that test is failing.

**Comment by PowerKiKi** [comment]
Scrutinizer static analysis is indeed lagging behind PhpStan. So there are a few false positives. However I find that it still have some value, especially for [code coverage statistics](https://scrutinizer-ci.com/g/genkgo/camt/statistics/), and preventing that it goes down.

IMHO I'd keep it while tolerating that i might be failing for the wrong reasons from time to time. Since integration and usage is very simple, I see it as a nice to have with minimal cost. I would probably not keep it if it becomes too much of a burden though...

**Comment by localheinz** [comment]
@PowerKiKi 

I use https://about.codecov.io for collecting and reporting code coverage - it is focussed and works like a charm. I vote for removing Scrutinizr.

**Comment by PowerKiKi** [comment]
Does it requires a login to view data ? I can't stand https://coveralls.io, because it hides everything behind a login :sob: 

Does it provide a code quality badge that we can proudly show off in the README ? :sunglasses: 

![image](https://user-images.githubusercontent.com/72603/218693690-0c2612ec-82a5-4121-bcab-3f8cb4bf6ccc.png)

**Comment by localheinz** [comment]
@PowerKiKi 

It does not show a code quality badge, no.

See #140!

**Comment by PowerKiKi** [comment]
@frederikbosch any opinion on the loss of code quality measurements ?

**Comment by frederikbosch** [comment]
No, I removed all style and code quality measurements from all my libraries. I found it a waste of time. I keep it with PHP-CS-Fixer and PHPStan.

**Comment by localheinz** [comment]
@PowerKiKi 

Perhaps https://github.com/psalm/shepherd could be of interest? You could display type coverage when using `vimeo/psalm`.

Here is an example from [`ergebnis/phpunit-slow-test-detector`](https://github.com/ergebnis/phpunit-slow-test-detector):

![CleanShot 2023-02-14 at 10 41 28@2x](https://user-images.githubusercontent.com/605483/218697995-ff525d4e-f2b8-446b-83e8-da740f18b34d.png)

**Comment by PowerKiKi** [comment]
I wouldn't replace 1 tool by 2 different tools. I guess only codecov will do then

**Comment by PowerKiKi** [comment]
Done via #140
