### ISSUE TITLE
Returning null instead of BadMethodCallException

### ISSUE THREAD

**Issue by toooni** [genkgo/camt#50]
First of all. Thank you for this great library.. It saved me a lot of hours.
The only "problem" I had was the handling of the `BadMethodCallException`'s. I do automatically end up catching way too much `BadMethodCallException` to only set a default value (mostly `null` by myself) in the catch block.
I know that changing this behaviour will cause a BC break. But are there any other reasons for that approach?

**Comment by frederikbosch** [comment]
@toooni I am not particular happy with some design decisions myself. I am planning to review the complete library after summer.

**Comment by toooni** [comment]
@frederikbosch just ping me if you need help in any way..

**Comment by roland-support-it** [comment]
Dear Frederik,

Same story here.

I had to comment out this:
**src\DTO\EntryTransactionDetail.php:...162:**
`     //   if ($this->remittanceInformation === null) {`
`    //       throw new BadMethodCallException()`
`     //   }`

and:	 
**src\DTO\RelatedParty.php:...45:**
`    //    if ($this->account === null) {`
`    //        throw new BadMethodCallException();`
`    //    }`


I tried to ignore or try/catch the Exception, but no succes.
Is there any way this can be implement in the orginal "genkgo" code?
Otherwise, every update I need to change it myself.
For me a NULL is enough, the "$this->account" variable is private so I can't check that one before.

**Comment by niki7har** [comment]
Same here.
Expecting null, getting BadMethodCallException...
Any reason the remittanceInformation must not be null/empty?

**Comment by Samuell1** [comment]
I had same issue, it will be better to return `null` if message is empty.

**Comment by PowerKiKi** [comment]
Would any of you create a PR, covered by tests, to implement this ?
