### ISSUE TITLE
Why are amounts converted into integers?

### ISSUE THREAD

**Issue by axelhuizinga** [genkgo/camt#93]
I wonder why 
/Decoder/Record.php 
Line 76:
$amount = StringToUnits::convert((string) $xmlEntry->Amt);
converts all amounts into int thus truncates the decimal value

**Comment by PowerKiKi** [comment]
See https://github.com/genkgo/camt/blob/3c8a24cef1f889ac29c4e27f09abe4fab4e6e149/test/Unit/Util/StringToUnitsTest.php#L24

 where you'll find out that amounts are expressed in an entire number of cents, and not a decimal number of the currency. This is a very critical thing to be aware of when using this lib, otherwise you'll think you have 100x more money that you actually have :money_mouth_face:
